bboard/bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/main/urls.py
from django.urls import path

from .views import index

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
]

bboard/main/models.py
from django.db import models

# Create your models here.

bboard/main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

bboard/main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">Объявления</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item"><a class="nav-link" href="#">Регистрация</a></li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Профиль</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Мои объявления</a>
                    <a class="dropdown-item" href="#">Изменить личные данные</a>
                    <a class="dropdown-item" href="#">Изменить пароль</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Выйти</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Удалить</a>
                </div>
            </li>
            <li class="nav-item"><a class="nav-link" href="#">Блог</a></li>
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column border">
            <a class="nav-link active" href="{% url 'main:index' %}">Главная</a>
            <span class="nav-link font-weight-bold">Недвижимость</span>
            <a class="nav-link" href="#">Квартиры</a>
            <a class="nav-link" href="#">Склады</a>
            <a class="nav-link" href="#">Гаражи</a>
            <span class="nav-link font-weight-bold">Транспорт</span>
            <a class="nav-link" href="#">Легковые автомобили</a>
            <a class="nav-link" href="#">Грузовые автомобили</a>
        </nav>
        <section class="col border py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy; Читатели.</p>
    </footer>
</body>
</html>

bboard/main/templates/main/index.html
{% extends "layout/basic.html" %}
{% block content %}
<h2>Последние 10 объявлений</h2>
{% endblock %}